#:kivy 2.3.1

BoxLayout:
    orientation: "vertical"

    Label:
        text: "Benvenuto nell'applicazione principale!"
        font_size: 24
        size_hint_y: 0.1

    Hello:  # Include il componente Hello
        size_hint_y: 0.1

    Input:  # Include il componente InputComponent
        size_hint_y: 0.3

    Users:  # Include il componente Users
        size_hint_y: 0.6

#    User:  # Include il componente User
#        id: user
#        size_hint_y: 0.9