#:kivy 2.3.1

<Input>:
    orientation: "vertical"
    spacing: 10
    padding: 10

    TextInput:
        id: text_input
        text: root.input_text
        hint_text: "Inserisci del testo"
        multiline: False
        on_text: root.input_text = self.text

    Button:
        text: "Invia"
        size_hint_y: None
        height: 40
        on_press: root.on_button_press()
	
	Label:
		id: output_label
		text: root.output_text
		font_size: 18
		size_hint_y: None
		height: 40
